name: sample_auth_server
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  googleapis: ^8.0.0
  googleapis_auth: ^1.1.0
  shelf: ^1.0.0
  shelf_router: ^1.0.0
  http: ^0.13.0
  dotenv: ^4.0.1

dev_dependencies:
  lints: ^2.0.0
